#!/usr/bin/env python3
"""Regenerate Sources/Logician/AgentGuideText.swift from docs/AGENT-GUIDE.md.

    python3 scripts/embed_agent_guide.py

The guide is served over MCP as the `logician://guide` resource, and a resource
has to work wherever the binary was copied to — an installed `logician` has no
repo around it and no side-car bundle guaranteed to travel with it. So the
markdown is compiled IN, as one raw string literal, and the generated file is
committed: `swift build -c release` stays a single command with no plugin, no
code generation step and nothing for CI to remember.

Drift is impossible rather than merely discouraged: `MCPResourceTests` reads
docs/AGENT-GUIDE.md off disk and asserts the constant matches it byte for byte,
so editing the guide without re-running this script fails the suite.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SOURCE = os.path.join(ROOT, "docs", "AGENT-GUIDE.md")
TARGET = os.path.join(ROOT, "Sources", "Logician", "AgentGuideText.swift")

HEADER = '''\
// GENERATED by scripts/embed_agent_guide.py — do not edit.
//
// docs/AGENT-GUIDE.md, compiled into the binary so the `logician://guide`
// resource works from an installed binary with no repo and no side-car bundle
// around it. Re-run the script after editing the guide; MCPResourceTests fails
// the build if the two ever disagree.

/// docs/AGENT-GUIDE.md, verbatim.
let agentGuideMarkdown = {open}
'''


def delimiter(text):
    """The shortest `#`-padded raw-string fence the guide cannot contain."""
    for pounds in range(1, 8):
        fence = '"""' + "#" * pounds
        if fence not in text:
            return "#" * pounds
    raise SystemExit("docs/AGENT-GUIDE.md defeats every raw-string delimiter tried")


def main():
    with open(SOURCE, encoding="utf-8") as handle:
        guide = handle.read()
    pounds = delimiter(guide)
    # A multiline literal drops the newline immediately before its closing
    # delimiter. Feed it one of our own so the guide's real last character —
    # its trailing newline — survives instead of being the one that is eaten.
    body = guide + "\n"
    rendered = (
        HEADER.format(open=pounds + '"""')
        + body
        + '"""' + pounds + "\n"
    )
    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    print("wrote %s (%d bytes of guide)" % (TARGET, len(guide.encode("utf-8"))))


if __name__ == "__main__":
    sys.exit(main())
