import Foundation

extension MCPServer {
    /// What `initialize` sends once per session, and the home of every rule
    /// that used to be copied into tool descriptions.
    ///
    /// It lives here rather than inline in `MCPServer.handle` for two reasons.
    /// The obvious one: a 5 KB string literal in the middle of the JSON-RPC
    /// switch buried the protocol logic. The paying one: this text is now the
    /// SINGLE copy of four cross-cutting notes — strip addressing, the two
    /// insert numberings, the `warning` key and the audio contract — that were
    /// previously appended to 14, 9, 28 and 4 tool descriptions respectively.
    /// A rule stated once and pointed at from the tools that obey it costs its
    /// bytes once per session instead of once per tool: `tools/list` fell from
    /// 151,028 to 143,102 bytes for the 2,417 bytes added here.
    ///
    /// It also has to carry a MAP now, which is why the six toolsets are named
    /// here. Claude Code (2.1.221) defers every MCP tool definition by
    /// transport — `isDeferredTool` returns true for anything `isMcp`, and
    /// `formatDeferredToolLine` is literally the tool's NAME — so a model on
    /// that client sees 83 bare names and this text, and nothing else, until
    /// it searches. Measured 2026-08-30: a BM25 probe over the surface
    /// (`scripts/retrieval_probe.py`) answers a query like 'quantize swing
    /// region' in one hop and a query like 'what is in this project' not at
    /// all, because one content word cannot discriminate between forty tools
    /// that all mention a project. The group names are the vocabulary that
    /// gap needs.
    ///
    /// What a COLD-START model needs before its first call, and nothing it can
    /// look up per tool. Still no FILE pointer: `docs/AGENT-GUIDE.md` is not
    /// reachable from an installed binary, and pointing at a path the client
    /// cannot open is worse than saying nothing. The guide is reachable as the
    /// `logician://guide` RESOURCE instead — compiled into the binary and named
    /// once below — so anything a client without resources support needs still
    /// lives here, and everything else can now be fetched rather than inlined.
    static let instructions: String =
        "Controls Logic Pro on this Mac over its control-surface protocol and macOS Accessibility (no coordinate-driven UI scripting). Needs Logic running with a project open, Accessibility granted, and a Mackie Control on the 'Logic MCP MCU' ports; English Logic UI assumed (v1) - logic_health's `logic_ui_language` says whether that assumption holds on this Mac and, when it does not, which planes degrade. Run logic_health FIRST - it starts the bridge daemon, checks every setup step and names the fix for whatever is missing - and logic_setup_key_commands once during onboarding, or Logic's Key Commands window flashes unannounced later.\n\n"
        + "WHAT IS HERE, in the six named groups the surface is built from. A client that DEFERS tool definitions shows you tool NAMES only until you search for one, so these are the words to search with when you do not know a tool's name. CORE, the mixing session: readiness, orientation reads, transport and playhead, channel strips, faders, mute/solo/pan, routing, sends, plugins and their parameters, and the offline bounces that let you HEAR a decision. REGIONS, the arrangement: regions (list, select, split, move, copy, rename, delete, quantize and the rest of the region inspector) plus markers and the track lifecycle. COMPOSITION, new material and new curves: MIDI recording, the Event List note editor, automation passes and reads, the tempo and meter maps, and loading instruments. DELIVERY, getting audio out: stems, bounce-in-place, silence stripping. PROJECT: save, open, new, duplicate, close, the reset, and the snapshot you diff against. KEYCOMMANDS: Logic's key commands and the raw control-surface escape hatch. A session can be launched with only some of them (`--toolsets`); the default is all 83 tools. When a name is not enough, `logic_find_tool` searches every tool's name, description and arguments by keyword and answers with full typed schemas - it covers the whole surface even when this session offers less of it.\n\n"
        + "RESULT CONTRACT (JSON in the text block). `success`: the intent landed - it can be FALSE while isError is false (a no-op refusal, a command that moved nothing), so read it: an error-free result is not automatically a successful one. `verified`: a readback or proof confirmed it - CAN be false while success is true; a few tools give it a tool-specific meaning, stated in their own description. `state`: a short token to branch on; the `already_*` family is a VERIFIED NO-OP - the target was already there and nothing was pressed, so it is no reason to retry, and if you expected a change your model of the project is stale. `warning`: ONE string naming something true and unwelcome about the result, several joined by ' ALSO: ' - read it BEFORE acting on the rest, and note that many tools advertise they MAY return it. A thrown failure carries isError true plus `error` and `error_code`: not_found, not_exposed, ambiguous, precondition_failed, verification_failed, write_failed, invalid_arguments, not_trusted, not_running, failed. Only SOME writes take a compare-and-set argument (expected_current_value, expected_current_db, expected_current_bpm, ... as each schema lists it), refusing with precondition_failed on a mismatch; the rest verify by readback only. Read before you write.\n\n"
        + "TWO PLANES. Logic is driven through its Accessibility tree AND through its Mackie Control surface. Accessibility needs the strip visible in an inspector and reaches only plugins that publish editable fields; the control surface reaches EVERY strip (Stereo Out, Master, auxes, buses) and EVERY plugin, custom-UI third-party included. Tools with `mcu` in the name are surface-only. The plugin tools (logic_list_inserts, logic_list_plugin_parameters, logic_set_plugin_parameter) take BOTH routes in one tool: they pick by the arguments you give — window_title means Accessibility, track_name + insert_slot means the surface — and every result says which ran in `route_used`. Pass `route` to force one. When in doubt, give the surface arguments.\n\n"
        + "STRIP ADDRESSING. Many tools' `track_name` also accepts a strip that has NO track header: 'Stereo Out', 'Master', 'Aux 1', bus names. Those are resolved and selected on the control surface (LCD name + SELECT LED verified before any write) instead of by track selection, so they need the MCU bridge, and `track_number` applies to tracks only. Use the name as Logic shows it in the Mixer, never the 6-character LCD abbreviation. A tool whose description says it is Accessibility-only reaches such a strip ONLY while an inspector is SHOWING it (select a track routed to it; opening the Mixer does NOT put a strip in reach — measured 2026-08-27, where 'Stereo Out' was visible as the selected track's output while 'Master' and 'Aux 1' were not). For every other strip take a surface route.\n\n"
        + "INSERT NUMBERING, the single most damaging confusion on this surface. `insert_index` is the ACCESSIBILITY ordinal — the occupied slots of the inspector's channel strip in order — and it is what logic_open_plugin, logic_close_plugin, logic_remove_plugin, logic_set_insert_bypass and logic_plugin_preset take. `insert_slot` is the MACKIE physical slot 1-8 and is what every logic_mcu_* tool, logic_record_automation, logic_read_automation and logic_evaluate_change take. They are DIFFERENT numberings and were observed REVERSED on an output strip (Stereo Out, 2026-08-27: AX Sensor/Limiter/Channel EQ, MCU Channel EQ/Limiter/Sensor). NEVER convert one into the other: list with the same tool and route you are about to write through. logic_list_inserts returns whichever numbering its `route_used` names.\n\n"
        + "CANNOT DO (v1): no note-level MIDI editing beyond logic_edit_event on the Event List; no plugin or instrument catalogue, so names must be exact as Logic spells them; no relative value changes (read, then write the absolute target; logic_set_track_volume's relative_db is the one exception); recording over occupied bars creates an OVERLAPPING region, it does not replace.\n\n"
        + "LONG TOOLS: the renders, bounces, snapshots and recordings emit MCP `notifications/progress` when you pass `_meta.progressToken`, and honour `notifications/cancelled` at their poll boundaries - a cancelled call unwinds through its own restore path and is never answered. Everything else stays responsive while one runs.\n\n"
        + "AUDIO RESULTS AND LISTENING: open a result's preview_path/clip_path with your client's FILE VIEWER (real multimodal audio in most clients), or call logic_get_audio_clip if your client forwards MCP audio blocks - a result arriving without its block means it does not. The tools that render audio attach it as MCP audio content blocks by default and take `include_audio: false` to skip that: pass it ONLY if your client stringifies content blocks it does not understand, where a few hundred KB of base64 becomes text instead of a sound; the file paths still come back and you listen by opening them. Every rendered file ALSO comes back as a `resource_link` to `logician://captures/<filename>` - `resources/read` fetches it on demand (base64, 8 MB cap; over that read the `.m4a` preview beside it), and the link is sent even with `include_audio: false`, so a client that cannot hear inline can still fetch what it wants. `resources/list` names the 50 most recent captures plus `logician://guide` - the full agent guide, with the workflows, failure modes and per-tool reference this text has no room for; READ IT when a task is more than one call. NEVER read audio files as text/bash. LISTEN FIRST, THEN READ THE NUMBERS: handed both the audio and the metadata, a model anchors on the metadata and reports region names, track names and metrics as things it HEARD - measured in a live multimodal round, and the one failure nothing in this server can detect for you. So logic_bounce_range, logic_render_track and logic_evaluate_change take `blind: true`: the result keeps its audio blocks, every file path and every safety field (`success`, `verified`, `state`, `warning`), and WITHHOLDS its measurements of the audio - peak/RMS, and an A/B's dB deltas - into the sealed JSON file named by `sealed_metrics_path`. If you CAN receive audio, pass blind: true on your FIRST listen of any material, say what you heard, and only then open the sealed file (nothing is re-rendered) or call again without blind. If you CANNOT receive audio - no audio block reached you and your client has no file viewer that passes audio to you - SAY THAT TO YOUR USER in plain words and stop: never claim to have heard what you did not receive, and never let metadata stand in for listening you did not do. Trust a result's metrics and warnings over your expectations, and report blocked steps instead of improvising. MIX BY EAR: fader and parameter VALUES are not loudness or quality - judge by listening, and use numbers only to confirm."
}
